version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - solita-dev-academy-2023-postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  solita-dev-academy-2023-postgres-db:
    driver: local
