version: '3.8'

services:
  postgres:
    container_name: solita-dev-academy-2023-postgres-container
    build:
      dockerfile: database/Dockerfile
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - solita-dev-academy-2023-postgres-db:/data/postgres
    ports:
      - "5432:5432"

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      args:
        # The system's environment variable for PUBLIC_API_ADDRESS
        # (usually from your .env file) is passed to the frontend
        # build (& run) container. This address is further passed
        # from the frontend container to HTTP clients, which use
        # this address to connect to the backend api.
        - PUBLIC_API_ADDRESS=$PUBLIC_API_ADDRESS
    ports:
      - "3001:3000"


volumes:
  solita-dev-academy-2023-postgres-db:
    driver: local
